# Generated by the release workflow in nickelsec/bough. Do not edit:
# the next release overwrites it.
class Bough < Formula
  desc "Draw what you built with Claude Code, Codex and Pi, and what it cost"
  homepage "https://www.bough.run"
  version "0.7.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/nickelsec/bough/releases/download/v0.7.1/bough_v0.7.1_darwin_arm64.tar.gz"
      sha256 "cab2b4d27832a1be08a82cb5f07d545e613b0c817adc7cb8657b04f77bb8f9ce"
    end
    on_intel do
      url "https://github.com/nickelsec/bough/releases/download/v0.7.1/bough_v0.7.1_darwin_amd64.tar.gz"
      sha256 "645f5304234c651900c5ab53ec809d1cc88cdeae00aac1711638488ade6d26e9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/nickelsec/bough/releases/download/v0.7.1/bough_v0.7.1_linux_arm64.tar.gz"
      sha256 "5e2563450ab20fb179fbfd7aac18d914b842b3790d4e7fc5e518d0c18abb39e1"
    end
    on_intel do
      url "https://github.com/nickelsec/bough/releases/download/v0.7.1/bough_v0.7.1_linux_amd64.tar.gz"
      sha256 "221b2f9e1d292f1c40b88f3a5a997314fdcd0861ed2ac710017e82f9a90eb670"
    end
  end

  # Homebrew strips the archive's single top directory before this
  # runs, so the binary is at the root by the time we get here.
  def install
    bin.install "bough"
    doc.install "README.md", "LICENSE"
  end

  test do
    assert_match "0.7.1", shell_output("#{bin}/bough --version")
  end
end
