# Generated by the release workflow in nickelsec/bough. Do not edit:
# the next release overwrites it.
class Bough < Formula
  desc "Draw what you built with Claude Code, Codex and Pi, and what it cost"
  homepage "https://www.bough.run"
  version "0.7.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/nickelsec/bough/releases/download/v0.7.0/bough_v0.7.0_darwin_arm64.tar.gz"
      sha256 "fdf416238974ff9f6391e8924941196b11c9c1d63999396efdcdc69987f5eed8"
    end
    on_intel do
      url "https://github.com/nickelsec/bough/releases/download/v0.7.0/bough_v0.7.0_darwin_amd64.tar.gz"
      sha256 "6241b6efe1aa4bc65a637e715b3ecffb777c5c877d6d66eab263a65bcd2c1591"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/nickelsec/bough/releases/download/v0.7.0/bough_v0.7.0_linux_arm64.tar.gz"
      sha256 "ea22b6eda5aea041db25e4692c18e1158351da61a94fecfacfae8c01755893f0"
    end
    on_intel do
      url "https://github.com/nickelsec/bough/releases/download/v0.7.0/bough_v0.7.0_linux_amd64.tar.gz"
      sha256 "664fce10b4c498cd10d509bea79044801fbb7e8370b38b517a30fac393da2362"
    end
  end

  # Homebrew strips the archive's single top directory before this
  # runs, so the binary is at the root by the time we get here.
  def install
    bin.install "bough"
    doc.install "README.md", "LICENSE"
  end

  test do
    assert_match "0.7.0", shell_output("#{bin}/bough --version")
  end
end
