# Generated by the release workflow in nickelsec/bough. Do not edit:
# the next release overwrites it.
class Bough < Formula
  desc "Draw what you built with Claude Code, Codex and Pi, and what it cost"
  homepage "https://www.bough.run"
  version "0.8.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/nickelsec/bough/releases/download/v0.8.0/bough_v0.8.0_darwin_arm64.tar.gz"
      sha256 "fc042b7b39b493c926b9a23c341471738e3eedeea296f172df9cce2427fdd0f0"
    end
    on_intel do
      url "https://github.com/nickelsec/bough/releases/download/v0.8.0/bough_v0.8.0_darwin_amd64.tar.gz"
      sha256 "b3c5b5cd0d5379e5cc60e443d05b4112f4aa58951b4395641dfa34888b7ef01f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/nickelsec/bough/releases/download/v0.8.0/bough_v0.8.0_linux_arm64.tar.gz"
      sha256 "f8c950fe04f04d9e8aa8b64e94d2360aa98bcb7e952c5bcc0783eec8349715b8"
    end
    on_intel do
      url "https://github.com/nickelsec/bough/releases/download/v0.8.0/bough_v0.8.0_linux_amd64.tar.gz"
      sha256 "0b8933b9ceaa7019b5accf6866b631a7210fae4d900b79aa53cb838470c341df"
    end
  end

  # Homebrew strips the archive's single top directory before this
  # runs, so the binary is at the root by the time we get here.
  def install
    bin.install "bough"
    doc.install "README.md", "LICENSE"
  end

  test do
    assert_match "0.8.0", shell_output("#{bin}/bough --version")
  end
end
